### ISSUE TITLE
Did you find a way to parse logs

### ISSUE THREAD

**Issue by liamgibbins** [TheRobBrennan/dji-flight-record-review#10]
Did you find a way to parse logs?

**Comment by TheRobBrennan** [comment]
Not yet. There was supposed to be an SDK release in winter 2021 to allow that. DJI has fallen behind, and I heard on a podcast that another third party (aside from Airdata - forget who) was supposed to have that ability in winter 2021 and they are waiting to hear more from DJI.

Bit of a bummer. I’d love to just see my data, ya know?

**Comment by howff** [comment]
DJI has just sent me their flight log parser. I've not had time to look at it yet, but I think the library is written in C++

![architectural](https://user-images.githubusercontent.com/3064316/200519163-09cf9f6c-c6f3-47b4-8028-bc17e2842ec4.png)

**Comment by TheRobBrennan** [comment]
@liamgibbins @howff is correct - I was just sent a similar library from DJI Developer Support.

I haven't tried it with the API key they have assigned me, however I will definitely give it a shot over the next few days. Hectic run of events here, but I am eager to see if it works.

The library has just been merged into the `main` branch as of now - from pull request https://github.com/TheRobBrennan/dji-flight-record-review/pull/12

**Comment by howff** [comment]
I had to make a few changes to the source code before it would compile. Then a few more changes to make it usable. Then when I put in my SDK key it didn't work `error code: 2 decription: invalid key`. I've sent a ticket to DJI so we'll see if they reply.

**Comment by TheRobBrennan** [comment]
Hmm what changes did you need to make @howff ? I see that I ran into an issue following their README:

`generate.sh: line 15: cmake: command not found`

Taking a look at the line in question from `dji/FR-1.0.2-V5/flightrecord-opensource/dji-flightrecord-kit/build/Mac/FRSample/generate.sh`, I see:

> cmake -D platform=${platform} -G "Xcode" -DENABLE_SHARED_LIB=false ${executableSourceFolder}

**Comment by howff** [comment]
That's not really an "issue", you'll need to install all the development tools into your environment first. A C++ compiler and cmake are among the tools you'll need.

An actual issue is that the code doesn't compile unless you change `dji-flightrecord-kit/source/FlightRecordStandardization/model/common/fr_standardization_common.cpp` to add the line `#include <cstdlib>`

You will also want to change `dji-flightrecord-kit/source/FRSample/main.cc` to add your own filename, and your own SDK key. If you change the filename into `argv[1]` then you can at least pass the filename as a command-line parameter.

No response from DJI yet on the 'invalid key' error message.

**Comment by TheRobBrennan** [comment]
Maybe this is just an issue trying to build on an Apple M1?

Here are the steps I followed:

```sh
# Example from the README building on macOS
#   ASSUMPTIONS:
#     - You are starting from the project root-level directory
#     - You have Xcode installed
#     - You have cmake installed
#       - TROUBLESHOOTING: If you receive "cmake: command not found":
#         - Download at https://cmake.org/download/ and install locally

# Navigate to the sample directory
% cd dji/FR-1.0.2-V5/flightrecord-opensource/dji-flightrecord-kit/build/Mac/FRSample

# Generate an Xcode project to work with
% sh generate.sh

# Select 1 to build an Xcode project

# Which do you want to build? Please Input the number:
# 0: Executable 1: Project        input: 1
# Start generate the project
# -- The C compiler identification is AppleClang 14.0.0.14000029
# -- The CXX compiler identification is AppleClang 14.0.0.14000029
# -- Detecting C compiler ABI info
# -- Detecting C compiler ABI info - done
# -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
# -- Detecting C compile features
# -- Detecting C compile features - done
# -- Detecting CXX compiler ABI info
# -- Detecting CXX compiler ABI info - done
# -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
# -- Detecting CXX compile features
# -- Detecting CXX compile features - done
# -O3 -DNDEBUG --std=c++11 -O0
# StandardizationCppHeader
# ...
# Build Static Lib
# -- ✅ start Mac operation in FlightRecordEngine
# mac
# -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
# -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
# -- Found Threads: TRUE
# Build Static Lib
# -- ✅ start Mac operation in DJIProtobuf
# -- Configuring done
# -- Generating done
# -- Build files have been written to: /Users/rob/repos/dji-flight-record-review/dji/FR-1.0.2-V5/flightrecord-opensource/dji-flightrecord-kit/build/Mac/FRSample
```

The Xcode project has been built 🎉

```sh
# Navigate to dji-flight-record-review/dji/FR-1.0.2-V5/flightrecord-opensource/dji-flightrecord-kit/build/Mac/FRSample

# From dji/FR-1.0.2-V5/flightrecord-opensource/README.md
#   - Open dji-flightrecord-kit/build/Mac/FRSample/FRSample.xcodeproj
#   - Go to the main.cc file and configure the path of the file you want to parse to the variable file_path.
#   - Configure the sdk key parameter of the 'startRequestParser' interface and you will be able to parse the file for the version of Flight Record 13
% open FRSample.xcodeproj
```

The Xcode project is built, but then errors out with this:
<img width="1380" alt="Screenshot 2022-12-04 at 7 35 57 PM" src="https://user-images.githubusercontent.com/4030490/205544195-ba02a25b-a335-4a80-99d6-9a1b0e09f77b.png">

**Comment by howff** [comment]
Maybe DJI have shipped the intel version of third party libraries not arm version. Try deleting all the .o and .a files under third-party and see if it rebuilds them natively. Check *.o files: `find third-party -name \*.o | xargs file` For example to delete *.a `find third-party -name \*.a -delete`

**Comment by mcihadarslanoglu** [comment]
Hello,

is there any update about parsing flight records?

**Comment by TheRobBrennan** [comment]
[@mcihadarslanoglu](https://github.com/mcihadarslanoglu) Sadly, no. I'm not interested in diving too deep at this point. There were compatibility issues with developing on  silicon, and I haven't the foggiest idea of the best path forward to resolving that. 😔

**Comment by howff** [comment]
The code is now available on github and has been updated a few times
https://github.com/dji-sdk/FlightRecordParsingLib

**Comment by mcihadarslanoglu** [comment]
@howff thank you so much for let us know.

**Comment by howff** [comment]
I applied for a new key on https://developer.dji.com/user
and I can confirm that the new code now works and decodes my FlightRecord :-)

There's a Dockerfile so you could build it on ubuntu and run it on your Mac?

It does seem to try and contact a web server when you run it, I've not found out which one yet.

**Comment by mcihadarslanoglu** [comment]
@howff I tried to run it on docker but I got error and opened an [issue](https://github.com/dji-sdk/FlightRecordParsingLib/issues/11) 

Can you let me know which columns there are in parsed log file ?

**Comment by howff** [comment]
It produces a massive JSON document, most of which is the elements of the `info.frameTimeStates` array, e.g. this entry picked from near the end:

```
  {
   "flightControllerState": {
    "attitude": {
     "pitch": 43,
     "roll": 0,
     "yaw": -441
    },
    "homeLocationCoordinate": {
     "latitude": 8.203456806327367,
     "longitude": 9.8946239787038954
    },
    "takeoffLocationAltitude": 1627.81152,
    "aircraftLocation": {
     "latitude": 8.203475400021425,
     "longitude": 9.8947259471900986
    },
    "altitude": -1.2,
    "flightMode": "ConfirmLanding",
    "GPSSignalLevel": "Level5",
    "satelliteCount": 26,
    "remainingFlightTime": 511,
    "batteryPercentageNeededToLandFromCurrentHeight": 5,
    "batteryPercentageNeededToGoHome": 0,
    "smartRTHState": "Idle",
    "behavior": "GoHome",
    "isFailsafeEnabled": false,
    "areMotorsOn": true,
    "isHomeLocationSet": true,
    "isLandingConfirmationNeeded": false,
    "hasReachedMaxFlightHeight": false,
    "hasReachedMaxFlightRadius": false,
    "windWarning": "Level0",
    "countOfFlights": 1,
    "flightLogIndex": 21,
    "isFlying": true,
    "smartRTHCountdown": 0,
    "velocity": {
     "velocityX": 0,
     "velocityY": 0,
     "velocityZ": 0
    },
    "isGPSBeingUsed": true,
    "flightTimeInSeconds": 455.80001831054688,
    "cumulativeFlightDistance": 1083.8706968107638
   },
   "cameraState": {
    "isRecording": false,
    "isShootingSinglePhoto": false,
    "isInserted": true,
    "isInitializing": false,
    "hasError": false,
    "isVerified": true,
    "isFull": true,
    "isFormatted": true,
    "isFormatting": false,
    "isInvalidFormat": false,
    "isReadOnly": false,
    "totalSpaceInMB": 122208,
    "remainingSpaceInMB": 29644,
    "availableCaptureCount": 7394,
    "availableRecordingTimeInSeconds": 2486,
    "index": 0,
    "mode": "RecordVideo"
   },
   "gimbalState": {
    "atitude": {
     "pitch": 0,
     "roll": 0,
     "yaw": -36.5
    },
    "fineTunedRoll": 0,
    "fineTunedPitch": 0,
    "fineTunedYaw": 0,
    "isRollAtStop": false,
    "isYawAtStop": false,
    "isPitchAtStop": false,
    "yawRelativeToAircraftHeading": 1.8999999761581421,
    "mode": "YawFollow",
    "index": 0
   },
   "rcHardwareState": {
    "leftStick": {
     "horizontalPosition": 0,
     "verticalPosition": 0
    },
    "rightStick": {
     "horizontalPosition": 0,
     "verticalPosition": 0
    },
    "leftWheel": 0,
    "rightWheel": {
     "isPresent": true,
     "isTurned": false,
     "isClicked": false,
     "value": 0
    },
    "flightModeSwitch": "Two",
    "goHomeButton": {
     "isPresent": true,
     "isClicked": false
    },
    "recordButton": {
     "isPresent": true,
     "isClicked": false
    },
    "shutterButton": {
     "isPresent": true,
     "isClicked": false
    },
    "style": "Unknown"
   },
   "batteryState": {
    "voltage": 7251,
    "current": -4753,
    "temperature": 34,
    "cellVoltages": [
     3639,
     3625
    ],
    "chargeRemainingInPercent": 33,
    "lowBatteryWarningThreshold": 20,
    "seriousLowBatteryWarningThreshold": 10,
    "index": -1,
    "lifetimeRemaining": 0,
    "designCapacity": 576000,
    "numberOfDischarges": 2560,
    "isInSingleBatteryMode": false,
    "fullChargeCapacity": 1913,
    "chargeRemaining": 621
   },
   "airLinkState": {
    "downlinkSignalQuality": 0,
    "hasDownlinkSignalQuality": false,
    "uplinkSignalQuality": 0,
    "hasUplinkSignalQuality": false
   },
   "visionState": {
    "collisionAvoidanceEnabled": false,
    "controlState": {
     "isAscentLimitedByObstacle": false,
     "isAvoidingActiveObstacleCollision": false,
     "isBraking": false,
     "isPerformingPrecisionLanding": false
    },
    "detectionStateMap": {}
   },
   "gimbalsState": {
    "0": {
     "atitude": {
      "pitch": 0,
      "roll": 0,
      "yaw": -36.5
     },
     "fineTunedRoll": 0,
     "fineTunedPitch": 0,
     "fineTunedYaw": 0,
     "isRollAtStop": false,
     "isYawAtStop": false,
     "isPitchAtStop": false,
     "yawRelativeToAircraftHeading": 1.8999999761581421,
     "mode": "YawFollow",
     "index": 0
    }
   },
   "camerasState": {
    "0": {
     "isRecording": false,
     "isShootingSinglePhoto": false,
     "isInserted": true,
     "isInitializing": false,
     "hasError": false,
     "isVerified": true,
     "isFull": true,
     "isFormatted": true,
     "isFormatting": false,
     "isInvalidFormat": false,
     "isReadOnly": false,
     "totalSpaceInMB": 122208,
     "remainingSpaceInMB": 29644,
     "availableCaptureCount": 7394,
     "availableRecordingTimeInSeconds": 2486,
     "index": 0,
     "mode": "RecordVideo"
    }
   },
   "batteriesState": {
    "0": {
     "voltage": 7251,
     "current": -4753,
     "temperature": 34,
     "cellVoltages": [
      3639,
      3625
     ],
     "chargeRemainingInPercent": 33,
     "lowBatteryWarningThreshold": 20,
     "seriousLowBatteryWarningThreshold": 10,
     "index": -1,
     "lifetimeRemaining": 0,
     "designCapacity": 576000,
     "numberOfDischarges": 2560,
     "isInSingleBatteryMode": false,
     "fullChargeCapacity": 1913,
     "chargeRemaining": 621
    }
   }
  }
```

Other elements may have a slightly different set of keys (especially take off vs flying vs landing).

**Comment by mcihadarslanoglu** [comment]
@howff I guess there is no data about lidar range finder, right?

**Comment by howff** [comment]
> @howff I guess there is no data about lidar range finder, right?

I don't know, there's a visionState object which has a detectionStateMap dict. You'll have to investigate yourself on your own log files and particular model of drone. This issue is about how to get parsing to work, and now it works the issue has been closed.

**Comment by TheRobBrennan** [comment]
This is great @howff  and @mcihadarslanoglu!!!

Any chance you might be able to share your Dockerfile as a PR - or in some shape? I'd love to see if I can get this to work on my M1 and update the repo here 🤩

Currently traveling but looking forward to seeing if this can work 🤞

**Comment by TheRobBrennan** [comment]
OMG it works! It works! It works!!!

Thank you @howff @mcihadarslanoglu 🙏🏻

**Comment by mcihadarslanoglu** [comment]
@TheRobBrennan you are welcome

**Comment by mcihadarslanoglu** [comment]
@TheRobBrennan we thank you too , as you mentioned us in your repository  🙏🏻
